### ISSUE TITLE
fullcalendar.js:15 Uncaught ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by fabuhelow** [Edofre/laravel-fullcalendar-scheduler#12]
jquery.js already imported, I can use it anywhere inside my project.

**Comment by Edofre** [comment]
Are you sure that jQuery is loaded before the calendar is generated?

**Comment by fabuhelow** [comment]
I have checked my code, the jQuery file is loaded after fullcal..js

My suggestion is, if we can control the position of JS fullcalender scripts rendering? for example at top or bottom.

Thanks,

**Comment by Edofre** [comment]
I could make it so people would be able to include the scripts themselves. Now the scripts get loaded when the calendar is generated. Just not sure when I would have time for this, maybe I'll try to look at it tonight.

**Comment by Edofre** [comment]
@fabuhelow 

If you update to the latest version (V1.2.0) you can specify in your config file that you don't want to include the script files, you can then call the following function after your jQuery to load the scripts.
```php
 \Edofre\FullcalendarScheduler\FullcalendarScheduler::renderScriptFiles(); 
```
