### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by AllCdnBoy** [Edofre/laravel-fullcalendar-scheduler#19]
tried on a couple different servers with the same result.  Just sits there with "Updating dependencies (including require-dev)" after running 
composer require edofre/laravel-fullcalendar-scheduler
or 
composer require edofre/laravel-fullcalendar-scheduler "v1.2.3"

after some time I get:
 Allowed memory size of 1610612736 bytes exhausted

I've installed many packages in the last couple days and this is the only one that hangs.

[update]
Now locked out of github because of "API rate limit" reached.

**Comment by AllCdnBoy** [comment]
I shouldn't have to increase the memory so much to get this installed .... not sure why this is a first time I've had to do this.

**Comment by Edofre** [comment]
@AllCdnBoy 

I think it's because of the fxp/composer-asset-plugin requirement. I'll have to start thinking about another way to deliver the js, might have users install it manually in their preferred way (dump in public or use npm f.e.).

**Comment by Dunrar** [comment]
@AllCdnBoy @Edofre Hey! So, did you find a way to solve this?
Edit: Solved it by installing the npm-asset/fullcalendar v3.8.0 requirement by hand.

**Comment by MukeshKumarMalhi** [comment]
@Edofre i want some help from you regards fullcalendar-schedular.
