### ISSUE TITLE
FatalErrorException (E_UNKNOWN) Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Parse error: syntax error, unexpected ''); ?>"></script>' (T_CONSTANT_ENCAPSED_STRING), expecting ',' or ')' (View: C:\wamp64\www\pronto_admin\vendor\edofre\laravel-fullcalendar-scheduler\src\views\files.blade.php) (View: C:\wamp64\www\pronto_admin\vendor\edofre\laravel-fullcalendar-scheduler\src\views\files.blade.php)

### ISSUE THREAD

**Issue by MukeshKumarMalhi** [Edofre/laravel-fullcalendar-scheduler#21]

**Comment by MukeshKumarMalhi** [comment]
@Edofre occuring this error when i use https://github.com/Edofre/laravel-fullcalendar-scheduler

**Comment by MukeshKumarMalhi** [comment]
@Edofre  how to resolve this error in blade?

**Comment by Edofre** [comment]
Can you share more information? What code are you using to render the calendar? Maybe share the code you're using in your view?

**Comment by MukeshKumarMalhi** [comment]
i was stuck in some issues regarding scheduler but now i had resolved them
all issues,
Edo Freriks  Thank you so much for reply
