### ISSUE TITLE
Could not find package bower-asset/fullcalendar at any version for your minimum-stability (stable)

### ISSUE THREAD

**Issue by aaxc** [Edofre/laravel-fullcalendar-scheduler#3]
This package seems to be using **_bower-asset/fullcalendar_**, that does not appear to be available :/

Or am I missing something big here?

**Comment by Edofre** [comment]
Hello @aaxc 

Do you have the fxp/composer-asset plugin installed?

You can install it using this command:
`composer global require "fxp/composer-asset-plugin:^1.2.0”`

This will add the fxp composer-asset-plugin and your composer will be able to find the bower-asset/fullcalendar package.
You can find more info on this page: https://packagist.org/packages/fxp/composer-asset-plugin

Let me know if this fixes the problem.

**Comment by aaxc** [comment]
Thank you for the quick answer, that worked and my schedule is up and running. Maybe you should add that to the README.md as an option? Cheers.

**Comment by Edofre** [comment]
I will add it to the readme, I've had this question before on another package :)

Glad you got it working!

**Comment by paskuale75** [comment]
After global required fxp added, any composer update become very slow !! Many npm CS repository to load !! Any solution ?
